CC = gcc
CFLAGS = -Iexternal/raylib/include -Iinclude
LDFLAGS = -Lexternal/raylib/lib -lraylib -lopengl32 -lgdi32 -lwinmm
ASAN = -fsanitize=address -g -O1

SRC := $(wildcard src/*.c)
OUT = main.exe

all:
	$(CC) $(CFLAGS) $(SRC) -o $(OUT) $(LDFLAGS)

clean:
	rm $(OUT)